name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_ui_auth: ^1.14.0
  provider: ^6.1.2
  cloud_firestore: ^4.17.5
  flutter:
    sdk: flutter
  go_router: ^14.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
